# Generated by Django 5.0.2 on 2024-06-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='e_responsibilities',
            field=models.CharField(max_length=500),
        ),
    ]
