# Generated by Django 5.0.2 on 2024-06-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_experience_e_responsibilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avator',
        ),
    ]
