# Generated by Django 5.0.2 on 2024-06-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cv_academic_experince_profile_referee_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=500)),
                ('p_describtion', models.TimeField(help_text='Enter a brief description of the project', max_length=10000)),
                ('p_duration', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
            ],
        ),
    ]
