# Generated by Django 5.0.2 on 2024-06-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='p_describtion',
            new_name='p_description',
        ),
    ]
