# Generated by Django 5.0.2 on 2024-06-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_p_describtion_project_p_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experince',
            new_name='Experience',
        ),
    ]
