# Generated by Django 5.0.2 on 2024-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_experince_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='p_duration',
            new_name='p_projectname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='p_name',
        ),
        migrations.AddField(
            model_name='project',
            name='p_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='p_startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_description',
            field=models.TextField(help_text='Enter a brief description of the project', max_length=10000),
        ),
    ]
